name: amap_map_fluttify
description: An `Amap` map component, based on `fluttify` engine.
version: 0.8.0+8d949d5
author: yohom <382146139@qq.com>
homepage: https://github.com/fluttify-project/amap_map_fluttify

environment:
  sdk: ">=2.2.2 <3.1.0"

dependencies:
  flutter:
    sdk: flutter
  foundation_fluttify: ^0.1.3
  amap_core_fluttify: ^0.1.0+4f403aa
  url_launcher: ^5.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: me.yohom.amap_map_fluttify
    pluginClass: AmapMapFluttifyPlugin
